# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Holding.destroy_all
User.destroy_all
Asset.destroy_all

Asset.create({ name: 'Apple', ticker: 'AAPL' })
Asset.create({ name: 'Amazon', ticker: 'AMZN' })
Asset.create({ name: 'Twitter', ticker: 'TWTR' })
Asset.create({ name: 'Microsoft', ticker: 'MSFT' })
Asset.create({ name: 'Citigroup', ticker: 'C' })
Asset.create({ name: 'Cisco', ticker: 'CSCO' })
Asset.create({ name: 'Alphabet', ticker: 'GOOG' })
Asset.create({ name: 'Chevron', ticker: 'CVX' })
Asset.create({ name: 'Costco', ticker: 'COST' })
Asset.create({ name: 'Comcast', ticker: 'CMCSA' })
Asset.create({ name: 'Carvana', ticker: 'CVNA' })
Asset.create({ name: 'Carnival', ticker: 'CCL' })
Asset.create({ name: 'Charter Communications', ticker: 'CHTR' })
Asset.create({ name: 'AMD', ticker: 'AMD' })
Asset.create({ name: 'Alibaba', ticker: 'BABA' })
Asset.create({ name: 'American Airlines', ticker: 'AAL' })
Asset.create({ name: 'AT&T', ticker: 'T' })
Asset.create({ name: 'Boeing', ticker: 'BA' })
Asset.create({ name: 'Bank of America', ticker: 'BAC' })
Asset.create({ name: 'Berkshire Hathaway', ticker: 'BRK.B' })
Asset.create({ name: 'Disney', ticker: 'DIS' })
Asset.create({ name: 'DocuSign', ticker: 'DOCU' })
Asset.create({ name: 'Delta Air Lines', ticker: 'DAL' })
Asset.create({ name: 'Draftkings', ticker: 'DKNG' })
Asset.create({ name: 'Deere', ticker: 'DE' })
Asset.create({ name: 'Datadog', ticker: 'DDOG' })
Asset.create({ name: 'Etsy', ticker: 'ETSY' })
Asset.create({ name: 'eBay', ticker: 'EBAY' })
Asset.create({ name: 'Estee Lauder', ticker: 'EL' })
Asset.create({ name: 'Ford Motor', ticker: 'F' })
Asset.create({ name: 'Facebook', ticker: 'FB' })
Asset.create({ name: 'Fastly', ticker: 'FSLY' })
Asset.create({ name: 'FedEx', ticker: 'FDX' })
Asset.create({ name: 'Fiserv', ticker: 'FISV' })
Asset.create({ name: 'Fidelity National Information', ticker: 'FIS' })
Asset.create({ name: 'Wells Fargo', ticker: 'WFC' })
Asset.create({ name: 'Gilead Sciences', ticker: 'GILD' })
Asset.create({ name: 'Goldman Sachs', ticker: 'GS' })
Asset.create({ name: 'Honeywell', ticker: 'HON' })
Asset.create({ name: 'Hilton Worldwide', ticker: 'HLT' })
Asset.create({ name: 'Halliburton', ticker: 'HAL' })
Asset.create({ name: 'Humana', ticker: 'HUM' })
Asset.create({ name: 'Booking Holdings', ticker: 'BKNG' })
Asset.create({ name: 'Intel', ticker: 'INTC' })
Asset.create({ name: 'Tesla', ticker: 'TSLA' })
Asset.create({ name: 'IBM', ticker: 'IBM' })
Asset.create({ name: 'Jacobs Engineering', ticker: 'J' })
Asset.create({ name: 'JD.com', ticker: 'JD' })
Asset.create({ name: 'JPMorgan Chase', ticker: 'JPM' })
Asset.create({ name: 'Johnson & Johnson', ticker: 'JNJ' })
Asset.create({ name: 'Johnson Controls', ticker: 'JCI' })
Asset.create({ name: 'Kellogg', ticker: 'K' })
Asset.create({ name: 'Kohl\'s', ticker: 'KSS' })
Asset.create({ name: 'KLA', ticker: 'KLAC' })
Asset.create({ name: 'Keysight Technologies', ticker: 'KEYS' })
Asset.create({ name: 'Kroger', ticker: 'KR' })
Asset.create({ name: 'Kimberly-Clark', ticker: 'KMB' })
Asset.create({ name: 'Keurig Dr Pepper', ticker: 'KDP' })
Asset.create({ name: 'Kodak', ticker: 'KODK' })
Asset.create({ name: 'Kraft Foods', ticker: 'KHC' })
Asset.create({ name: 'Lowe\'s', ticker: 'LOW' })
Asset.create({ name: 'Livongo', ticker: 'LVGO' })
Asset.create({ name: 'Lam Research', ticker: 'LRCX' })
Asset.create({ name: 'Lyft', ticker: 'LYFT' })
Asset.create({ name: 'Lululemon', ticker: 'LULU' })
Asset.create({ name: 'Lockheed', ticker: 'LMT' })
Asset.create({ name: 'Linde', ticker: 'LIN' })
Asset.create({ name: 'Eli Lilly', ticker: 'LLY' })
Asset.create({ name: 'Macy\'s', ticker: 'M' })
Asset.create({ name: 'Mastercard', ticker: 'MA' })
Asset.create({ name: 'Moderna', ticker: 'MRNA' })
Asset.create({ name: 'Micron Technology', ticker: 'MU' })
Asset.create({ name: 'McDonald\'s', ticker: 'MCD' })
Asset.create({ name: 'Merck', ticker: 'MRK' })
Asset.create({ name: 'NVIDIA', ticker: 'NVDA' })
Asset.create({ name: 'Netflix', ticker: 'NFLX' })
Asset.create({ name: 'Novavax', ticker: 'NVAX' })
Asset.create({ name: 'NIO', ticker: 'NIO' })
Asset.create({ name: 'Nikola', ticker: 'NKLA' })
Asset.create({ name: 'Nike', ticker: 'NKE' })
Asset.create({ name: 'Newmont', ticker: 'NEM' })
Asset.create({ name: 'Norwegian Cruise Line', ticker: 'NCLH' })
Asset.create({ name: 'Occidental Petroleum', ticker: 'OXY' })
Asset.create({ name: 'Okta', ticker: 'OKTA' })
Asset.create({ name: 'Ollie\'s Bargain Outlet', ticker: 'OLLI' })
Asset.create({ name: 'O\'Reilly Auto Parts', ticker: 'ORLY' })
Asset.create({ name: 'Old Dominion Freight Line', ticker: 'ODFL' })
Asset.create({ name: 'PayPal', ticker: 'PYPL' })
Asset.create({ name: 'Pinduoduo', ticker: 'PDD' })
Asset.create({ name: 'Procter & Gamble', ticker: 'PG' })
Asset.create({ name: 'Pfizer', ticker: 'PFE' })
Asset.create({ name: 'Plug Power', ticker: 'PLUG' })
Asset.create({ name: 'Pinterest', ticker: 'PINS' })
Asset.create({ name: 'Penn National Gaming', ticker: 'PENN' })
Asset.create({ name: 'Qualcomm', ticker: 'QCOM' })
Asset.create({ name: 'Quidel', ticker: 'QDEL' })
Asset.create({ name: 'Qorvo', ticker: 'QRVO' })
Asset.create({ name: 'Qiagen', ticker: 'QGEN' })
Asset.create({ name: 'Ryder', ticker: 'R' })
Asset.create({ name: 'Roku', ticker: 'ROKU' })
Asset.create({ name: 'Royal Caribbean Group', ticker: 'RCL' })
Asset.create({ name: 'Rocket Companies', ticker: 'RKT' })
Asset.create({ name: 'Raytheon Technologies', ticker: 'RTX' })
Asset.create({ name: 'Regeneron', ticker: 'REGN' })
Asset.create({ name: 'RingCentral', ticker: 'RNG' })
Asset.create({ name: 'Ross', ticker: 'ROST' })
Asset.create({ name: 'Shopify', ticker: 'SHOP' })
Asset.create({ name: 'Square', ticker: 'SQ' })
Asset.create({ name: 'Sorrento Therapeutics', ticker: 'SRNE' })
Asset.create({ name: 'Sea Limited', ticker: 'SE' })
Asset.create({ name: 'Target', ticker: 'TGT' })
Asset.create({ name: 'Teladoc Health', ticker: 'TDOC' })
Asset.create({ name: 'T-Mobile', ticker: 'TMUS' })
Asset.create({ name: 'United Airlines', ticker: 'UAL' })
Asset.create({ name: 'Uber', ticker: 'UBER' })
Asset.create({ name: 'UnitedHealth', ticker: 'UNH' })
Asset.create({ name: 'UPS', ticker: 'UPS' })
Asset.create({ name: 'Union Pacific', ticker: 'UNP' })
Asset.create({ name: 'Visa', ticker: 'V' })
Asset.create({ name: 'Verizon', ticker: 'VZ' })
Asset.create({ name: 'Varian', ticker: 'VAR' })
Asset.create({ name: 'Wayfair', ticker: 'W' })
Asset.create({ name: 'Walmart', ticker: 'WMT' })
Asset.create({ name: 'Wynn Resorts', ticker: 'WYNN' })
Asset.create({ name: 'Wix.com', ticker: 'WIX' })
Asset.create({ name: 'Workhorse', ticker: 'WKHS' })
Asset.create({ name: 'Workday', ticker: 'WDAY' })
Asset.create({ name: 'Walgreens', ticker: 'WBA' })
Asset.create({ name: 'Western Digital', ticker: 'WDC' })
Asset.create({ name: 'United States Steel', ticker: 'X' })
Asset.create({ name: 'Xilinx', ticker: 'XLNX' })
Asset.create({ name: 'Xcel Energy', ticker: 'XEL' })
Asset.create({ name: 'Exxon Mobil', ticker: 'XOM' })
Asset.create({ name: 'Yandex', ticker: 'YNDX' })
Asset.create({ name: 'Yum!', ticker: 'YUM' })
Asset.create({ name: 'Zillow', ticker: 'Z' })
Asset.create({ name: 'Zoom', ticker: 'ZM' })
Asset.create({ name: 'Zscaler', ticker: 'ZS' })
Asset.create({ name: 'Zoetis', ticker: 'ZTS' })
Asset.create({ name: 'Zynga', ticker: 'ZNGA' })
Asset.create({ name: 'Zendesk', ticker: 'ZEN' })
Asset.create({ name: 'ZoomInfo', ticker: 'ZI' })
Asset.create({ name: 'Zebra Technologies', ticker: 'ZBRA' })

















User.create({ username: "Guest", password: "showmethemoney" })
User.create({ username: "Jack", password: "jfjfjf" })
User.create({ username: "Tammy", password: "jfjfjf" })
User.create({ username: "Luke", password: "jfjfjf" })